use_frameworks!

platform :ios, '10.0'

target 'YDBlockKit_Example' do
  pod 'YDBlockKit', :path => '../'

  target 'YDBlockKit_Tests' do
    inherit! :search_paths

    pod 'FBSnapshotTestCase'
  end
end
